//! Schematic and PCB record types for the v2 API.
//!
//! Each record type is generated by the `#[altium_record]` proc macro,
//! which replaces the struct body with a backing-store field and generates
//! getters, setters, builders, and `RecordType` trait implementation.

// ---------------------------------------------------------------------------
// Schematic enums
// ---------------------------------------------------------------------------

pub mod enums;

// ---------------------------------------------------------------------------
// Schematic record types (Track 3A)
// ---------------------------------------------------------------------------

pub mod sch_arc;
pub mod sch_bezier;
pub mod sch_component;
pub mod sch_designator;
pub mod sch_ellipse;
pub mod sch_elliptical_arc;
pub mod sch_image;
pub mod sch_line;
pub mod sch_map_definer;
pub mod sch_map_definer_list;
pub mod sch_parameter;
pub mod sch_pie;
pub mod sch_pin;
pub mod sch_polygon;
pub mod sch_polyline;
pub mod sch_rectangle;
pub mod sch_round_rectangle;

// ---------------------------------------------------------------------------
// Schematic record types (Track 3B)
// ---------------------------------------------------------------------------

pub mod sch_blanket;
pub mod sch_bus;
pub mod sch_bus_entry;
pub mod sch_implementation;
pub mod sch_implementation_list;
pub mod sch_implementation_parameters;
pub mod sch_junction;
pub mod sch_label;
pub mod sch_net_label;
pub mod sch_no_erc;
pub mod sch_note;
pub mod sch_port;
pub mod sch_power;
pub mod sch_sheet;
pub mod sch_sheet_entry;
pub mod sch_sheet_filename;
pub mod sch_sheet_name;
pub mod sch_sheet_symbol;
pub mod sch_symbol;
pub mod sch_task_holder;
pub mod sch_text_frame;
pub mod sch_wire;

// ---------------------------------------------------------------------------
// Re-exports: enums
// ---------------------------------------------------------------------------

pub use enums::*;

// ---------------------------------------------------------------------------
// Re-exports: schematic record types
// ---------------------------------------------------------------------------

pub use sch_arc::SchArcRecord;
pub use sch_bezier::SchBezierRecord;
pub use sch_component::SchComponentRecord;
pub use sch_designator::SchDesignatorRecord;
pub use sch_ellipse::SchEllipseRecord;
pub use sch_elliptical_arc::SchEllipticalArcRecord;
pub use sch_image::SchImageRecord;
pub use sch_line::SchLineRecord;
pub use sch_map_definer::SchMapDefinerRecord;
pub use sch_map_definer_list::SchMapDefinerListRecord;
pub use sch_parameter::SchParameterRecord;
pub use sch_pie::SchPieRecord;
pub use sch_pin::SchPinRecord;
pub use sch_polygon::SchPolygonRecord;
pub use sch_polyline::SchPolylineRecord;
pub use sch_rectangle::SchRectangleRecord;
pub use sch_round_rectangle::SchRoundRectangleRecord;

// ---------------------------------------------------------------------------
// Re-exports: schematic record types (Track 3B)
// ---------------------------------------------------------------------------

pub use sch_blanket::SchBlanketRecord;
pub use sch_bus::SchBusRecord;
pub use sch_bus_entry::SchBusEntryRecord;
pub use sch_implementation::SchImplementationRecord;
pub use sch_implementation_list::SchImplementationListRecord;
pub use sch_implementation_parameters::SchImplementationParametersRecord;
pub use sch_junction::SchJunctionRecord;
pub use sch_label::SchLabelRecord;
pub use sch_net_label::SchNetLabelRecord;
pub use sch_no_erc::SchNoERCRecord;
pub use sch_note::SchNoteRecord;
pub use sch_port::SchPortRecord;
pub use sch_power::SchPowerRecord;
pub use sch_sheet::SchSheetRecord;
pub use sch_sheet_entry::SchSheetEntryRecord;
pub use sch_sheet_filename::SchSheetFileNameRecord;
pub use sch_sheet_name::SchSheetNameRecord;
pub use sch_sheet_symbol::SchSheetSymbolRecord;
pub use sch_symbol::SchSymbolRecord;
pub use sch_task_holder::SchTaskHolderRecord;
pub use sch_text_frame::SchTextFrameRecord;
pub use sch_wire::SchWireRecord;

// ---------------------------------------------------------------------------
// PCB record types (Track 3C)
// ---------------------------------------------------------------------------

pub mod pcb_arc;
pub mod pcb_component_body;
pub mod pcb_fill;
pub mod pcb_footprint;
pub mod pcb_pad;
pub mod pcb_region;
pub mod pcb_text;
pub mod pcb_track;
pub mod pcb_via;

// ---------------------------------------------------------------------------
// Re-exports: PCB record types
// ---------------------------------------------------------------------------

pub use pcb_arc::PcbArcRecord;
pub use pcb_component_body::PcbComponentBodyRecord;
pub use pcb_fill::PcbFillRecord;
pub use pcb_footprint::PcbFootprintRecord;
pub use pcb_pad::PcbPadRecord;
pub use pcb_region::PcbRegionRecord;
pub use pcb_text::PcbTextRecord;
pub use pcb_track::PcbTrackRecord;
pub use pcb_via::PcbViaRecord;

// ---------------------------------------------------------------------------
// Re-exports: PCB custom parse functions
// ---------------------------------------------------------------------------

pub(crate) use pcb_arc::parse_arc;
pub(crate) use pcb_component_body::parse_component_body;
pub(crate) use pcb_fill::parse_fill;
pub(crate) use pcb_pad::parse_pad;
pub(crate) use pcb_region::parse_region;
pub(crate) use pcb_text::parse_text;
pub(crate) use pcb_track::parse_track;
pub(crate) use pcb_via::parse_via;

// ---------------------------------------------------------------------------
// Utility functions
// ---------------------------------------------------------------------------

/// Get the record ID from a parameter collection.
pub fn record_id_for_params(params: &crate::v2::parameters::ParameterCollection) -> Option<u8> {
    params.get("RECORD").map(|v| v.as_int_or(0) as u8)
}

/// Returns true when the schematic record ID has a typed v2 model.
pub(crate) fn is_supported_sch_record_id(record_id: u8) -> bool {
    matches!(
        record_id,
        1 | 2
            | 3
            | 4
            | 5
            | 6
            | 7
            | 8
            | 9
            | 11
            | 12
            | 13
            | 14
            | 17
            | 18
            | 22
            | 25
            | 26
            | 27
            | 28
            | 29
            | 30
            | 31
            | 32
            | 33
            | 34
            | 37
            | 39
            | 41
            | 43
            | 44
            | 45
            | 46
            | 47
            | 48
            | 209
            | 225
    )
}

// ---------------------------------------------------------------------------
// Tests (Wave 3 macro tests)
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    // -----------------------------------------------------------------------
    // altium_enum tests
    // -----------------------------------------------------------------------

    #[altium_format_derive::altium_enum]
    #[derive(Copy, Clone, Debug, PartialEq, Eq)]
    pub enum TestOrientation {
        Up = 0,
        Right = 1,
        Down = 2,
        Left = 3,
    }

    #[test]
    fn enum_from_int() {
        use crate::v2::traits::AltiumEnum;
        assert_eq!(TestOrientation::from_int(0), TestOrientation::Up);
        assert_eq!(TestOrientation::from_int(1), TestOrientation::Right);
        assert_eq!(TestOrientation::from_int(2), TestOrientation::Down);
        assert_eq!(TestOrientation::from_int(3), TestOrientation::Left);
    }

    #[test]
    fn enum_to_int() {
        use crate::v2::traits::AltiumEnum;
        assert_eq!(TestOrientation::Up.to_int(), 0);
        assert_eq!(TestOrientation::Right.to_int(), 1);
    }

    #[test]
    fn enum_fallback() {
        use crate::v2::traits::AltiumEnum;
        // Unknown value falls back to first variant
        assert_eq!(TestOrientation::from_int(99), TestOrientation::Up);
    }

    #[test]
    fn enum_param_codec() {
        use crate::v2::parameters::ParameterCollection;
        use crate::v2::traits::ParamCodec;

        let mut params = ParameterCollection::new();
        TestOrientation::Right.write(&mut params, "ORIENTATION");

        let read_back = TestOrientation::read(&params, "ORIENTATION");
        assert_eq!(read_back, Some(TestOrientation::Right));
    }

    // Test with custom fallback
    #[altium_format_derive::altium_enum(fallback = "Unknown")]
    #[derive(Copy, Clone, Debug, PartialEq, Eq)]
    pub enum TestWithFallback {
        Normal = 0,
        Special = 1,
        Unknown = 255,
    }

    #[test]
    fn enum_custom_fallback() {
        use crate::v2::traits::AltiumEnum;
        assert_eq!(TestWithFallback::from_int(99), TestWithFallback::Unknown);
    }

    // Test with explicit altium(value) attribute
    #[altium_format_derive::altium_enum]
    #[derive(Copy, Clone, Debug, PartialEq, Eq)]
    pub enum TestExplicitValues {
        #[altium(value = 10)]
        First,
        #[altium(value = 20)]
        Second,
        #[altium(value = 30)]
        Third,
    }

    #[test]
    fn enum_explicit_values() {
        use crate::v2::traits::AltiumEnum;
        assert_eq!(TestExplicitValues::from_int(10), TestExplicitValues::First);
        assert_eq!(TestExplicitValues::from_int(20), TestExplicitValues::Second);
        assert_eq!(TestExplicitValues::from_int(30), TestExplicitValues::Third);
        assert_eq!(TestExplicitValues::First.to_int(), 10);
        assert_eq!(TestExplicitValues::Second.to_int(), 20);
    }

    // -----------------------------------------------------------------------
    // altium_record tests (param-based)
    // -----------------------------------------------------------------------

    #[altium_format_derive::altium_record(kind = "sch", record_id = 99, codec = "params")]
    struct TestRecord {
        #[altium(key = "NAME")]
        name: String,

        #[altium(key = "VALUE")]
        value: i32,
    }

    #[test]
    fn record_struct_replaced_with_origin() {
        // Verify the struct only has an `origin` field (backing store).
        use crate::v2::backing_store::{ParamOrigin, RecordOrigin};
        let origin = RecordOrigin::Param(ParamOrigin::new("|RECORD=99|NAME=Test|VALUE=42|"));
        let rec = TestRecord::from_origin(origin);
        // If struct had extra fields this wouldn't compile.
        let _origin_ref = &rec.origin;
    }

    #[test]
    fn record_getter_reads_from_backing_store() {
        use crate::v2::backing_store::{ParamOrigin, RecordOrigin};
        let origin = RecordOrigin::Param(ParamOrigin::new("|RECORD=99|NAME=Test|VALUE=42|"));
        let rec = TestRecord::from_origin(origin);
        assert_eq!(rec.name(), "Test");
        assert_eq!(rec.value(), 42);
    }

    #[test]
    fn record_try_getter() {
        use crate::v2::backing_store::{ParamOrigin, RecordOrigin};
        let origin = RecordOrigin::Param(ParamOrigin::new("|RECORD=99|NAME=Hello|"));
        let rec = TestRecord::from_origin(origin);
        assert_eq!(rec.try_name(), Some("Hello".to_string()));
        // VALUE is missing, try_getter should return None
        assert_eq!(rec.try_value(), None);
    }

    #[test]
    fn record_setter_writes_to_backing_store() {
        use crate::v2::backing_store::{ParamOrigin, RecordOrigin};
        let origin = RecordOrigin::Param(ParamOrigin::new("|RECORD=99|NAME=Test|VALUE=42|"));
        let mut rec = TestRecord::from_origin(origin);
        rec.set_name("Updated".to_string());
        assert_eq!(rec.name(), "Updated");
        rec.set_value(100);
        assert_eq!(rec.value(), 100);
    }

    #[test]
    fn record_update_closure() {
        use crate::v2::backing_store::{ParamOrigin, RecordOrigin};
        let origin = RecordOrigin::Param(ParamOrigin::new("|RECORD=99|NAME=Test|VALUE=42|"));
        let mut rec = TestRecord::from_origin(origin);
        let old_name = rec.update_name(|n| {
            let old = n.clone();
            *n = "Modified".to_string();
            old
        });
        assert_eq!(old_name, "Test");
        assert_eq!(rec.name(), "Modified");
    }

    #[test]
    fn record_builder() {
        use crate::v2::backing_store::{ParamOrigin, RecordOrigin};
        fn template() -> RecordOrigin {
            RecordOrigin::Param(ParamOrigin::new("|RECORD=99|"))
        }
        let rec = TestRecord::builder(template)
            .name("Built".to_string())
            .value(77)
            .build();
        assert_eq!(rec.name(), "Built");
        assert_eq!(rec.value(), 77);
    }

    #[test]
    fn record_type_trait() {
        use crate::v2::traits::RecordType;
        assert_eq!(TestRecord::RECORD_ID, 99);

        use crate::v2::backing_store::{ParamOrigin, RecordOrigin};
        let origin = RecordOrigin::Param(ParamOrigin::new("|RECORD=99|NAME=X|"));
        let rec = TestRecord::from_origin(origin);
        // Verify origin() returns reference to the backing store
        let _origin = rec.origin();
    }

    #[test]
    fn record_getter_default_for_missing_key() {
        use crate::v2::backing_store::{ParamOrigin, RecordOrigin};
        // Create a record with only RECORD key, no NAME or VALUE
        let origin = RecordOrigin::Param(ParamOrigin::new("|RECORD=99|"));
        let rec = TestRecord::from_origin(origin);
        // Getters should return default values for missing keys
        assert_eq!(rec.name(), ""); // String::default()
        assert_eq!(rec.value(), 0); // i32::default()
    }

    // -----------------------------------------------------------------------
    // altium_record tests (param-based with skip)
    // -----------------------------------------------------------------------

    #[altium_format_derive::altium_record(kind = "sch", record_id = 98, codec = "params")]
    struct TestRecordWithSkip {
        #[altium(key = "VISIBLE")]
        visible: bool,

        #[altium(skip)]
        _internal: i32,
    }

    #[test]
    fn record_skip_field() {
        use crate::v2::backing_store::{ParamOrigin, RecordOrigin};
        let origin = RecordOrigin::Param(ParamOrigin::new("|RECORD=98|VISIBLE=T|"));
        let rec = TestRecordWithSkip::from_origin(origin);
        assert!(rec.visible());
        // _internal should have no getter/setter generated
    }
}
