[package]
name = "autopcb-ir"
version = "0.2.0"
edition = "2024"
rust-version = "1.85"

[lints]
workspace = true

[dependencies]
altium-format = { version = "0.2.0", path = "../altium-format" }
altium-format-spec = { version = "0.2.0", path = "../altium-format-spec" }
altium-format-types = { version = "0.2.0", path = "../altium-format-types" }
autopcb-routes = { version = "0.2.0", path = "../autopcb-routes" }
indexmap = "2"
thiserror = "2"
serde = { version = "1.0", features = ["derive"], optional = true }

[features]
test-fixtures = []
serde = ["dep:serde", "altium-format-types/serde"]
