[package]
name = "autopcb-shell"
version = "0.2.0"
edition = "2024"
rust-version = "1.85"

[lints]
workspace = true

[dependencies]
autopcb-ir = { version = "0.2.0", path = "../autopcb-ir" }
autopcb-placement = { version = "0.2.0", path = "../autopcb-placement" }
altium-format = { version = "0.2.0", path = "../altium-format" }
efame = { package = "eframe", version = "0.33", features = ["wgpu", "persistence"] }
egui_tiles = { version = "0.14", features = ["serde"] }
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
