//! Schematic and PCB record types for the v2 API.
//!
//! Each record type is generated by the `#[altium_record]` proc macro,
//! which replaces the struct body with a backing-store field and generates
//! getters, setters, builders, and `RecordType` trait implementation.

// ---------------------------------------------------------------------------
// Schematic enums
// ---------------------------------------------------------------------------

pub mod enums;

// ---------------------------------------------------------------------------
// Schematic record types
// ---------------------------------------------------------------------------

/// Declares schematic record modules, re-exports, and generates
/// `is_supported_sch_record_id` from a single source of truth.
macro_rules! sch_records {
    ($( $mod:ident :: $ty:ident ),* $(,)?) => {
        $( pub mod $mod; )*
        $( pub use $mod::$ty; )*

        /// Returns true when the schematic record ID has a typed v2 model.
        pub(crate) fn is_supported_sch_record_id(record_id: u8) -> bool {
            use $crate::traits::RecordType;
            match record_id {
                $( _ if record_id == <$ty as RecordType>::RECORD_ID => true, )*
                _ => false,
            }
        }
    };
}

sch_records! {
    // Track 3A – drawing primitives & component structure
    sch_arc::SchArcRecord,
    sch_bezier::SchBezierRecord,
    sch_component::SchComponentRecord,
    sch_designator::SchDesignatorRecord,
    sch_ellipse::SchEllipseRecord,
    sch_elliptical_arc::SchEllipticalArcRecord,
    sch_image::SchImageRecord,
    sch_line::SchLineRecord,
    sch_map_definer::SchMapDefinerRecord,
    sch_map_definer_list::SchMapDefinerListRecord,
    sch_parameter::SchParameterRecord,
    sch_pie::SchPieRecord,
    sch_pin::SchPinRecord,
    sch_polygon::SchPolygonRecord,
    sch_polyline::SchPolylineRecord,
    sch_rectangle::SchRectangleRecord,
    sch_round_rectangle::SchRoundRectangleRecord,

    // Track 3B – connectivity, hierarchy & annotations
    sch_blanket::SchBlanketRecord,
    sch_bus::SchBusRecord,
    sch_bus_entry::SchBusEntryRecord,
    sch_implementation::SchImplementationRecord,
    sch_implementation_list::SchImplementationListRecord,
    sch_implementation_parameters::SchImplementationParametersRecord,
    sch_junction::SchJunctionRecord,
    sch_label::SchLabelRecord,
    sch_net_label::SchNetLabelRecord,
    sch_no_erc::SchNoERCRecord,
    sch_note::SchNoteRecord,
    sch_port::SchPortRecord,
    sch_power::SchPowerRecord,
    sch_sheet::SchSheetRecord,
    sch_sheet_entry::SchSheetEntryRecord,
    sch_sheet_filename::SchSheetFileNameRecord,
    sch_sheet_name::SchSheetNameRecord,
    sch_sheet_symbol::SchSheetSymbolRecord,
    sch_symbol::SchSymbolRecord,
    sch_task_holder::SchTaskHolderRecord,
    sch_text_frame::SchTextFrameRecord,
    sch_wire::SchWireRecord,
}

// ---------------------------------------------------------------------------
// Re-exports: enums
// ---------------------------------------------------------------------------

pub use enums::*;

// ---------------------------------------------------------------------------
// PCB record types (Track 3C)
// ---------------------------------------------------------------------------

pub mod pcb_arc;
pub mod pcb_component_body;
pub mod pcb_connection;
pub mod pcb_fill;
pub mod pcb_footprint;
pub mod pcb_pad;
pub mod pcb_region;
pub mod pcb_text;
pub mod pcb_track;
pub mod pcb_via;

// ---------------------------------------------------------------------------
// Re-exports: PCB record types
// ---------------------------------------------------------------------------

pub use pcb_arc::PcbArcRecord;
pub use pcb_component_body::PcbComponentBodyRecord;
pub use pcb_connection::PcbConnectionRecord;
pub use pcb_fill::PcbFillRecord;
pub use pcb_footprint::PcbFootprintRecord;
pub use pcb_pad::PcbPadRecord;
pub use pcb_region::PcbRegionRecord;
pub use pcb_text::PcbTextRecord;
pub use pcb_track::PcbTrackRecord;
pub use pcb_via::PcbViaRecord;

// ---------------------------------------------------------------------------
// Re-exports: PCB custom parse functions
// ---------------------------------------------------------------------------

pub(crate) use pcb_arc::parse_arc;
pub(crate) use pcb_component_body::parse_component_body;
pub(crate) use pcb_connection::parse_connection;
pub(crate) use pcb_fill::parse_fill;
pub(crate) use pcb_pad::parse_pad;
pub(crate) use pcb_region::parse_region;
pub(crate) use pcb_text::parse_text;
pub(crate) use pcb_track::parse_track;
pub(crate) use pcb_via::parse_via;

// ---------------------------------------------------------------------------
// Utility functions
// ---------------------------------------------------------------------------

/// Get the record ID from a parameter collection.
pub fn record_id_for_params(params: &crate::parameters::ParameterCollection) -> Option<u8> {
    params.get("RECORD").map(|v| v.as_int_or(0) as u8)
}

// ---------------------------------------------------------------------------
// Tests (Wave 3 macro tests)
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    // -----------------------------------------------------------------------
    // altium_enum tests
    // -----------------------------------------------------------------------

    #[altium_format_derive::altium_enum]
    #[derive(Copy, Clone, Debug, PartialEq, Eq)]
    pub enum TestOrientation {
        Up = 0,
        Right = 1,
        Down = 2,
        Left = 3,
    }

    #[test]
    fn enum_from_int() {
        use crate::traits::AltiumEnum;
        assert_eq!(TestOrientation::from_int(0), TestOrientation::Up);
        assert_eq!(TestOrientation::from_int(1), TestOrientation::Right);
        assert_eq!(TestOrientation::from_int(2), TestOrientation::Down);
        assert_eq!(TestOrientation::from_int(3), TestOrientation::Left);
    }

    #[test]
    fn enum_to_int() {
        use crate::traits::AltiumEnum;
        assert_eq!(TestOrientation::Up.to_int(), 0);
        assert_eq!(TestOrientation::Right.to_int(), 1);
    }

    #[test]
    fn enum_fallback() {
        use crate::traits::AltiumEnum;
        // Unknown value falls back to first variant
        assert_eq!(TestOrientation::from_int(99), TestOrientation::Up);
    }

    #[test]
    fn enum_param_codec() {
        use crate::parameters::ParameterCollection;
        use crate::traits::ParamCodec;

        let mut params = ParameterCollection::new();
        TestOrientation::Right.write(&mut params, "ORIENTATION");

        let read_back = TestOrientation::read(&params, "ORIENTATION").unwrap();
        assert_eq!(read_back, Some(TestOrientation::Right));
    }

    // Test with custom fallback
    #[altium_format_derive::altium_enum(fallback = "Unknown")]
    #[derive(Copy, Clone, Debug, PartialEq, Eq)]
    pub enum TestWithFallback {
        Normal = 0,
        Special = 1,
        Unknown = 255,
    }

    #[test]
    fn enum_custom_fallback() {
        use crate::traits::AltiumEnum;
        assert_eq!(TestWithFallback::from_int(99), TestWithFallback::Unknown);
    }

    // Test with explicit altium(value) attribute
    #[altium_format_derive::altium_enum]
    #[derive(Copy, Clone, Debug, PartialEq, Eq)]
    pub enum TestExplicitValues {
        #[altium(value = 10)]
        First,
        #[altium(value = 20)]
        Second,
        #[altium(value = 30)]
        Third,
    }

    #[test]
    fn enum_explicit_values() {
        use crate::traits::AltiumEnum;
        assert_eq!(TestExplicitValues::from_int(10), TestExplicitValues::First);
        assert_eq!(TestExplicitValues::from_int(20), TestExplicitValues::Second);
        assert_eq!(TestExplicitValues::from_int(30), TestExplicitValues::Third);
        assert_eq!(TestExplicitValues::First.to_int(), 10);
        assert_eq!(TestExplicitValues::Second.to_int(), 20);
    }

    // -----------------------------------------------------------------------
    // altium_record tests (param-based)
    // -----------------------------------------------------------------------

    #[altium_format_derive::altium_record(kind = "sch", record_id = 99, codec = "params")]
    struct TestRecord {
        #[altium(key = "NAME")]
        name: String,

        #[altium(key = "VALUE")]
        value: i32,
    }

    #[test]
    fn record_struct_replaced_with_origin() {
        // Verify the struct only has an `origin` field (backing store).
        use crate::backing_store::{ParamOrigin, RecordOrigin};
        let origin = RecordOrigin::Param(ParamOrigin::new("|RECORD=99|NAME=Test|VALUE=42|"));
        let rec = TestRecord::from_origin(origin);
        // If struct had extra fields this wouldn't compile.
        let _origin_ref = &rec.origin;
    }

    #[test]
    fn record_getter_reads_from_backing_store() {
        use crate::backing_store::{ParamOrigin, RecordOrigin};
        let origin = RecordOrigin::Param(ParamOrigin::new("|RECORD=99|NAME=Test|VALUE=42|"));
        let rec = TestRecord::from_origin(origin);
        assert_eq!(rec.name().unwrap(), "Test");
        assert_eq!(rec.value().unwrap(), 42);
    }

    #[test]
    fn record_try_getter() {
        use crate::backing_store::{ParamOrigin, RecordOrigin};
        let origin = RecordOrigin::Param(ParamOrigin::new("|RECORD=99|NAME=Hello|"));
        let rec = TestRecord::from_origin(origin);
        assert_eq!(rec.try_name().unwrap(), Some("Hello".to_string()));
        // VALUE is missing, try_getter should return None
        assert_eq!(rec.try_value().unwrap(), None);
    }

    #[test]
    fn record_setter_writes_to_backing_store() {
        use crate::backing_store::{ParamOrigin, RecordOrigin};
        let origin = RecordOrigin::Param(ParamOrigin::new("|RECORD=99|NAME=Test|VALUE=42|"));
        let mut rec = TestRecord::from_origin(origin);
        rec.set_name("Updated".to_string());
        assert_eq!(rec.name().unwrap(), "Updated");
        rec.set_value(100);
        assert_eq!(rec.value().unwrap(), 100);
    }

    #[test]
    fn record_update_closure() {
        use crate::backing_store::{ParamOrigin, RecordOrigin};
        let origin = RecordOrigin::Param(ParamOrigin::new("|RECORD=99|NAME=Test|VALUE=42|"));
        let mut rec = TestRecord::from_origin(origin);
        let old_name = rec.update_name(|n| {
            let old = n.clone();
            *n = "Modified".to_string();
            old
        });
        assert_eq!(old_name.unwrap(), "Test");
        assert_eq!(rec.name().unwrap(), "Modified");
    }

    #[test]
    fn record_builder() {
        use crate::backing_store::{ParamOrigin, RecordOrigin};
        fn template() -> RecordOrigin {
            RecordOrigin::Param(ParamOrigin::new("|RECORD=99|"))
        }
        let rec = TestRecord::builder(template)
            .name("Built".to_string())
            .value(77)
            .build();
        assert_eq!(rec.name().unwrap(), "Built");
        assert_eq!(rec.value().unwrap(), 77);
    }

    #[test]
    fn record_type_trait() {
        use crate::traits::RecordType;
        assert_eq!(TestRecord::RECORD_ID, 99);

        use crate::backing_store::{ParamOrigin, RecordOrigin};
        let origin = RecordOrigin::Param(ParamOrigin::new("|RECORD=99|NAME=X|"));
        let rec = TestRecord::from_origin(origin);
        // Verify origin() returns reference to the backing store
        let _origin = rec.origin();
    }

    #[test]
    fn record_getter_default_for_missing_key() {
        use crate::backing_store::{ParamOrigin, RecordOrigin};
        // Create a record with only RECORD key, no NAME or VALUE
        let origin = RecordOrigin::Param(ParamOrigin::new("|RECORD=99|"));
        let rec = TestRecord::from_origin(origin);
        // Getters should return default values for missing keys
        assert_eq!(rec.name().unwrap(), ""); // String::default()
        assert_eq!(rec.value().unwrap(), 0); // i32::default()
    }

    // -----------------------------------------------------------------------
    // altium_record tests (param-based with skip)
    // -----------------------------------------------------------------------

    #[altium_format_derive::altium_record(kind = "sch", record_id = 98, codec = "params")]
    struct TestRecordWithSkip {
        #[altium(key = "VISIBLE")]
        visible: bool,

        #[altium(skip)]
        _internal: i32,
    }

    #[test]
    fn record_skip_field() {
        use crate::backing_store::{ParamOrigin, RecordOrigin};
        let origin = RecordOrigin::Param(ParamOrigin::new("|RECORD=98|VISIBLE=T|"));
        let rec = TestRecordWithSkip::from_origin(origin);
        assert!(rec.visible().unwrap());
        // _internal should have no getter/setter generated
    }
}
