use serde::{Deserialize, Serialize};

use crate::baseline::SyncBaseline;
use crate::digest::Digest;
use crate::identity::BindingId;
use crate::snapshot::ArtifactKind;

pub const PLAN_SCHEMA_VERSION: u32 = 1;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum PlanDirection {
    Compile,
    Dump,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum PlanStatus {
    Ready,
    Blocked,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ChangeDisposition {
    SourceOnly,
    DocumentOnly,
    SameChange,
    Conflict,
    Unchanged,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ChangeKind {
    Add,
    Update,
    Delete,
    Rename,
    Noop,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct SemanticChange {
    pub binding: BindingId,
    pub resource_kind: String,
    pub resource_key: String,
    pub disposition: ChangeDisposition,
    pub change_kind: ChangeKind,
    pub source_before: Option<Digest>,
    pub source_after: Option<Digest>,
    pub document_before: Option<Digest>,
    pub document_after: Option<Digest>,
    pub reason: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ArtifactPrecondition {
    /// Exact authored source bytes at plan time. `None` means the source file did
    /// not exist during adoption/dump planning.
    pub source_raw_digest: Option<Digest>,
    /// Semantic document snapshot at plan time. Generated management annotation
    /// IDs are excluded from this digest.
    pub document_semantic_digest: Option<Digest>,
    pub baseline_digest: Option<Digest>,
}

/// Exact mutation payload generated by the planner.
///
/// The semantic ECO is a view over this payload. `apply` never re-runs the
/// planner and never reconstructs mutation intent from the ECO.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "target", rename_all = "snake_case")]
pub enum ArtifactPatch {
    Document {
        /// Fully elaborated, import-free concrete spec produced during planning.
        concrete_spec: String,
        expected_semantic_digest: Digest,
    },
    Source {
        /// Final lossless source bytes after structured CST merge.
        text: String,
        expected_raw_digest: Digest,
    },
    None,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct PlanBundle {
    pub schema_version: u32,
    pub plan_id: String,
    pub artifact_kind: ArtifactKind,
    pub direction: PlanDirection,
    pub status: PlanStatus,
    pub precondition: ArtifactPrecondition,
    pub changes: Vec<SemanticChange>,
    pub patch: ArtifactPatch,
    /// Baseline to commit only after the patch has staged, validated, reopened,
    /// and passed semantic postcondition verification.
    pub next_baseline: SyncBaseline,
}

impl PlanBundle {
    pub fn new(
        artifact_kind: ArtifactKind,
        direction: PlanDirection,
        precondition: ArtifactPrecondition,
        changes: Vec<SemanticChange>,
        patch: ArtifactPatch,
        next_baseline: SyncBaseline,
    ) -> Self {
        let status = if changes
            .iter()
            .any(|change| change.disposition == ChangeDisposition::Conflict)
        {
            PlanStatus::Blocked
        } else {
            PlanStatus::Ready
        };
        Self {
            schema_version: PLAN_SCHEMA_VERSION,
            plan_id: format!("{:032x}", rand::random::<u128>()),
            artifact_kind,
            direction,
            status,
            precondition,
            changes,
            patch,
            next_baseline,
        }
    }

    pub fn has_changes(&self) -> bool {
        !matches!(self.patch, ArtifactPatch::None)
    }

    pub fn conflicts(&self) -> impl Iterator<Item = &SemanticChange> {
        self.changes
            .iter()
            .filter(|change| change.disposition == ChangeDisposition::Conflict)
    }
}
