//! View types and wrappers for the v2 API.
//!
//! View types provide ergonomic, lifetime-bounded access to the underlying
//! record data stored in the backing store. There are two categories:
//!
//! - **Leaf wrappers**: Thin `Deref`/`DerefMut` wrappers around a single
//!   record type, generated by [`impl_leaf_wrapper!`].
//! - **Parent wrappers**: Compound views over a parent record and its
//!   children (e.g., [`SchComponentView`] wraps a component and its pins).
//!
//! Each view type has a corresponding [`WrapperFamily`] marker enum that
//! ties the record type to its view, enabling type-safe query APIs like
//! `doc.query::<SchPin>(q)`.

pub mod leaf_wrappers;
pub mod sch_component_view;
pub mod pcb_footprint_view;
pub mod child_handle;

pub use leaf_wrappers::*;
pub use sch_component_view::*;
pub use pcb_footprint_view::*;
pub use child_handle::*;

#[cfg(test)]
mod tests {
    use super::*;
    use crate::v2::backing_store::{
        ComponentGroup, ParamOrigin, RecordNode, RecordOrigin,
    };

    // -----------------------------------------------------------------------
    // Leaf wrapper tests
    // -----------------------------------------------------------------------

    #[test]
    fn leaf_wrapper_deref() {
        // Create a SchPinRecord, wrap in SchPinView, access getter via Deref.
        let origin = RecordOrigin::Param(ParamOrigin::new(
            "|RECORD=2|Designator=1|Name=VCC|PinLength=30|",
        ));
        let mut record = crate::v2::records::SchPinRecord::from_origin(origin);
        let view = SchPinView::new(&mut record);

        // Deref allows calling record getters directly on the view.
        assert_eq!(view.name(), crate::v2::newtypes::PinName::from("VCC"));
        assert_eq!(
            view.designator(),
            crate::v2::newtypes::Designator::from("1")
        );
    }

    #[test]
    fn leaf_wrapper_deref_mut() {
        // Modify a record through its leaf view wrapper.
        let origin = RecordOrigin::Param(ParamOrigin::new(
            "|RECORD=2|Designator=1|Name=VCC|PinLength=30|",
        ));
        let mut record = crate::v2::records::SchPinRecord::from_origin(origin);

        {
            let mut view = SchPinView::new(&mut record);
            view.set_name(crate::v2::newtypes::PinName::from("GND"));
        }

        assert_eq!(record.name(), crate::v2::newtypes::PinName::from("GND"));
    }

    // -----------------------------------------------------------------------
    // SchComponentView tests
    // -----------------------------------------------------------------------

    #[test]
    fn component_view_child_count() {
        // Create a ComponentGroup with a component and two pin children.
        let comp_origin =
            RecordOrigin::Param(ParamOrigin::new("|RECORD=1|LibReference=Resistor|"));
        let comp = RecordNode::new(1, comp_origin);

        let pin1_origin = RecordOrigin::Param(ParamOrigin::new("|RECORD=2|Name=VCC|"));
        let pin1 = RecordNode::new(2, pin1_origin);

        let pin2_origin = RecordOrigin::Param(ParamOrigin::new("|RECORD=2|Name=GND|"));
        let pin2 = RecordNode::new(2, pin2_origin);

        // Add a non-pin child (e.g., designator, RECORD=34).
        let desig_origin =
            RecordOrigin::Param(ParamOrigin::new("|RECORD=34|Name=Designator|"));
        let desig = RecordNode::new(34, desig_origin);

        let mut group = ComponentGroup::new(comp, vec![pin1, pin2, desig], vec![1, 2, 3]);

        let (component, children) = group.split_borrow();
        let view = SchComponentView::new(component, children);

        assert_eq!(view.child_count(), 3);
        assert_eq!(view.pin_count(), 2);
    }

    #[test]
    fn component_view_split_borrow() {
        // Verify that split() allows simultaneous access to component and children.
        let comp_origin =
            RecordOrigin::Param(ParamOrigin::new("|RECORD=1|LibReference=Cap|"));
        let comp = RecordNode::new(1, comp_origin);

        let pin_origin = RecordOrigin::Param(ParamOrigin::new("|RECORD=2|Name=A|"));
        let pin = RecordNode::new(2, pin_origin);

        let mut group = ComponentGroup::new(comp, vec![pin], vec![1]);

        let (component, children) = group.split_borrow();
        let mut view = SchComponentView::new(component, children);

        // Split: modify both simultaneously.
        let (comp_node, child_slice) = view.split();
        comp_node.mark_dirty();
        child_slice[0].mark_dirty();

        assert!(comp_node.is_dirty());
        assert!(child_slice[0].is_dirty());
    }

    // -----------------------------------------------------------------------
    // ChildHandle basics
    // -----------------------------------------------------------------------

    #[test]
    fn child_handle_basics() {
        use std::marker::PhantomData;

        // Verify ChildKey, ChildHandle, ChildResults can be constructed.
        let _key: ChildKey<SchPin> = ChildKey {
            index: 0,
            _marker: PhantomData,
        };

        let mut nodes = vec![
            RecordNode::new(
                2,
                RecordOrigin::Param(ParamOrigin::new("|RECORD=2|Name=A|")),
            ),
            RecordNode::new(
                2,
                RecordOrigin::Param(ParamOrigin::new("|RECORD=2|Name=B|")),
            ),
        ];

        let _handle: ChildHandle<'_, SchPin> = ChildHandle {
            children: &mut nodes,
            index: 0,
            _marker: PhantomData,
        };

        let results: ChildResults<'_, SchPin> = ChildResults {
            children: &mut [],
            indices: vec![0, 1],
            _marker: PhantomData,
        };

        assert_eq!(results.len(), 2);
        assert!(!results.is_empty());

        let empty_results: ChildResults<'_, SchPin> = ChildResults {
            children: &mut [],
            indices: vec![],
            _marker: PhantomData,
        };

        assert!(empty_results.is_empty());
    }
}
