[package]
name = "autopcb-viewer"
version = "0.2.0"
edition = "2024"
rust-version = "1.85"

[lints]
workspace = true

[dependencies]
autopcb-ir = { version = "0.2.0", path = "../autopcb-ir" }
altium-format = { version = "0.2.0", path = "../altium-format" }
eframe = { version = "0.33", features = ["wgpu"] }
egui-wgpu = "0.33"
wgpu = "27"
bytemuck = { version = "1", features = ["derive"] }
image = { version = "0.25", default-features = false, features = ["png"] }
anyhow = "1.0"
